INSERT INTO equipment VALUES (1000, 'Resistance Bands/Cables');
INSERT INTO equipment VALUES (1001, 'Heavy Ropes');
INSERT INTO equipment VALUES (1002, 'Cones');
INSERT INTO equipment VALUES (1003, 'Kettlebells');
INSERT INTO equipment VALUES (1004, 'Medicine Ball');
INSERT INTO equipment VALUES (1005, 'No Equipment');
INSERT INTO equipment VALUES (1006, 'Ladder');
INSERT INTO equipment VALUES (1007, 'Bench');
INSERT INTO equipment VALUES (1008, 'Dumbbells');
INSERT INTO equipment VALUES (1009, 'Weight Machines / Selectorized');
INSERT INTO equipment VALUES (1010, 'Barbell');
INSERT INTO equipment VALUES (1011, 'BOSU Trainer');
INSERT INTO equipment VALUES (1012, 'Stability Ball');
INSERT INTO equipment VALUES (1013, 'Raised Platform/Box');
INSERT INTO equipment VALUES (1014, 'Pull up bar');
INSERT INTO equipment VALUES (1015, 'Hurdles');
INSERT INTO equipment VALUES (1016, 'TRX');
INSERT INTO equipment VALUES (1017, 'Equipment');
INSERT INTO muscle VALUES (1000, 'Body/Integrated');
INSERT INTO muscle VALUES (1001, 'Calves');
INSERT INTO muscle VALUES (1002, 'Shins');
INSERT INTO muscle VALUES (1003, 'Thighs');
INSERT INTO muscle VALUES (1004, 'ABS');
INSERT INTO muscle VALUES (1005, 'Butt/Hips');
INSERT INTO muscle VALUES (1006, 'Shoulders');
INSERT INTO muscle VALUES (1007, 'Back');
INSERT INTO muscle VALUES (1008, 'Chest');
INSERT INTO muscle VALUES (1009, 'Arms');
INSERT INTO muscle VALUES (1010, 'Neck');
